const games = [
  {
    id: 1,
  title: "Cyberpunk 2077",
  price: 9.99,
  originalPrice: 59.99,
  discount: 83,
  platform: "PC",
  genre: "RPG",
  image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/capsule_616x353.jpg",
  imageHor: "images/games/cyberpunk-g/cyberpunk-horizontal.jpg",
  imageVer: "images/games/cyberpunk-g/cyberpunk-vertical.jpg",
  description: "Cyberpunk 2077 is an open-world action-RPG set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. Between you and your goal stands the entire city of Night City and its shadows.",
  featured: true,
  developer: "CD PROJEKT RED",
  publisher: "CD PROJEKT RED",
  releaseDate: "December 10, 2020",
  reviewScore: 86,
  reviewCount: "204,000",
  reviewText: "Very Positive",
  media: [
    { type: "video", src: "images/screenshots/cyberpunk-s/cyberpunk-trailer1.mp4", thumb: "images/screenshots/cyberpunk-s/cyberpunk-thumb1.jpg" },
    { type: "video", src: "images/screenshots/cyberpunk-s/cyberpunk-trailer2.mp4", thumb: "images/screenshots/cyberpunk-s/cyberpunk-thumb2.jpg" },
    { type: "image", src: "images/screenshots/cyberpunk-s/cyberpunk-ss1.jpg", thumb: "images/screenshots/cyberpunk-s/cyberpunk-ss1.jpg" },
    { type: "image", src: "images/screenshots/cyberpunk-s/cyberpunk-ss2.jpg", thumb: "images/screenshots/cyberpunk-s/cyberpunk-ss2.jpg" },
    { type: "image", src: "images/screenshots/cyberpunk-s/cyberpunk-ss3.jpg", thumb: "images/screenshots/cyberpunk-s/cyberpunk-ss3.jpg" },
    { type: "image", src: "images/screenshots/cyberpunk-s/cyberpunk-ss4.jpg", thumb: "images/screenshots/cyberpunk-s/cyberpunk-ss4.jpg" },
    { type: "image", src: "images/screenshots/cyberpunk-s/cyberpunk-ss5.jpg", thumb: "images/screenshots/cyberpunk-s/cyberpunk-ss5.jpg" }
  ],
    systemReqs: {
      min: [
        ["OS", "Windows 10 64-bit"],
        ["CPU", "Intel Core i7-6700 / AMD Ryzen 5 1600"],
        ["RAM", "12 GB RAM"],
        ["GPU", "NVIDIA GTX 1060 6 GB / RX 580 8 GB"],
        ["DirectX", "Version 12"],
        ["Network", "Broadband Internet"],
        ["Storage", "70 GB SSD"]
      ],
      rec: [
        ["OS", "Windows 10 64-bit"],
        ["CPU", "Intel Core i7-8700K / AMD Ryzen 5 3600"],
        ["RAM", "16 GB RAM"],
        ["GPU", "NVIDIA RTX 2060 Super / RX 5700 XT"],
        ["DirectX", "Version 12"],
        ["Network", "Broadband Internet"],
        ["Storage", "70 GB SSD"]
      ]
    }
  },
  {
    id: 2,
    title: "The Witcher 3: Wild Hunt",
    price: 4.99,
    originalPrice: 29.99,
    discount: 83,
    platform: "PC",
    genre: "RPG",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/292030/capsule_616x353.jpg",
    imageHor: "images/games/witcher-g/witcher-horizontal.jpg",
    imageVer: "images/games/witcher-g/witcher-vertical.jpg",
    description: "You are a professional monster hunter. Your goal is to find a child of prophecy in a vast open fantasy world. Stop risen wraiths, take contracts in the most dangerous corners of the world and come to the aid of those in need. Explore thousands of miles of wilderness and over 100 cities, villages and castles.",
    featured: true,
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    releaseDate: "May 18, 2015",
    reviewScore: 97,
    reviewCount: "312,000",
    reviewText: "Overwhelmingly Positive",
    media: [
      { type: "video", src: "images/screenshots/witcher-s/witcher3-trailer1.mp4", thumb: "images/screenshots/witcher-s/witcher3-thumb1.jpg" },
      { type: "video", src: "images/screenshots/witcher-s/witcher3-trailer2.mp4", thumb: "images/screenshots/witcher-s/witcher3-thumb2.jpg" },
      { type: "image", src: "images/screenshots/witcher-s/witcher3-ss1.jpg", thumb: "images/screenshots/witcher-s/witcher3-ss1.jpg" },
      { type: "image", src: "images/screenshots/witcher-s/witcher3-ss2.jpg", thumb: "images/screenshots/witcher-s/witcher3-ss2.jpg" },
      { type: "image", src: "images/screenshots/witcher-s/witcher3-ss3.jpg", thumb: "images/screenshots/witcher-s/witcher3-ss3.jpg" },
      { type: "image", src: "images/screenshots/witcher-s/witcher3-ss4.jpg", thumb: "images/screenshots/witcher-s/witcher3-ss4.jpg" },
      { type: "image", src: "images/screenshots/witcher-s/witcher3-ss5.jpg", thumb: "images/screenshots/witcher-s/witcher3-ss5.jpg" }
    ],
    systemReqs: {
      min: [
        ["OS", "Windows 7 64-bit"],
        ["CPU", "Intel Core i5-2500K / AMD Phenom II X4 940"],
        ["RAM", "6 GB RAM"],
        ["GPU", "NVIDIA GTX 660 / AMD Radeon HD 7870"],
        ["DirectX", "Version 11"],
        ["Network", "Broadband Internet"],
        ["Storage", "35 GB"]
      ],
      rec: [
        ["OS", "Windows 10 64-bit"],
        ["CPU", "Intel Core i7-3770 / AMD FX-8350"],
        ["RAM", "8 GB RAM"],
        ["GPU", "NVIDIA GTX 770 / AMD Radeon R9 290"],
        ["DirectX", "Version 11"],
        ["Network", "Broadband Internet"],
        ["Storage", "35 GB"]
      ]
    }
  },
  {
    id: 3,
    title: "Red Dead Redemption 2",
    price: 19.99,
    originalPrice: 59.99,
    discount: 67,
    platform: "PC",
    genre: "Action",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1174180/capsule_616x353.jpg",
    imageHor: "images/games/redemption-g/redemption-horizontal.jpg",
    imageVer: "images/games/redemption-g/redemption-vertical.jpg",
    description: "An epic tale of honor and loyalty at the dawn of the modern era. America, 1899. The age of outlaws and gunslingers is coming to an end. Arthur Morgan and the Van der Linde gang must survive in an increasingly hostile world.",
    featured: true,
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    releaseDate: "December 5, 2019",
    reviewScore: 93,
    reviewCount: "174,000",
    reviewText: "Very Positive",
    media: [
      { type: "video", src: "images/screenshots/redemption-s/rdr2-trailer1.mp4", thumb: "images/screenshots/redemption-s/rdr2-thumb1.jpg" },
      { type: "video", src: "images/screenshots/redemption-s/rdr2-trailer2.mp4", thumb: "images/screenshots/redemption-s/rdr2-thumb2.jpg" },
      { type: "image", src: "images/screenshots/redemption-s/rdr2-ss1.jpg", thumb: "images/screenshots/redemption-s/rdr2-ss1.jpg" },
      { type: "image", src: "images/screenshots/redemption-s/rdr2-ss2.jpg", thumb: "images/screenshots/redemption-s/rdr2-ss2.jpg" },
      { type: "image", src: "images/screenshots/redemption-s/rdr2-ss3.jpg", thumb: "images/screenshots/redemption-s/rdr2-ss3.jpg" },
      { type: "image", src: "images/screenshots/redemption-s/rdr2-ss4.jpg", thumb: "images/screenshots/redemption-s/rdr2-ss4.jpg" },
      { type: "image", src: "images/screenshots/redemption-s/rdr2-ss5.jpg", thumb: "images/screenshots/redemption-s/rdr2-ss5.jpg" }
    ],
    systemReqs: {
      min: [
        ["OS", "Windows 10 64-bit"],
        ["CPU", "Intel Core i5-2500K / AMD FX-6300"],
        ["RAM", "8 GB RAM"],
        ["GPU", "NVIDIA GTX 770 2 GB / AMD R9 280 3 GB"],
        ["DirectX", "Version 11"],
        ["Network", "Broadband Internet"],
        ["Storage", "150 GB SSD"]
      ],
      rec: [
        ["OS", "Windows 10 64-bit"],
        ["CPU", "Intel Core i7-4770K / AMD Ryzen 5 1500X"],
        ["RAM", "12 GB RAM"],
        ["GPU", "NVIDIA GTX 1060 6 GB / AMD RX 480 4 GB"],
        ["DirectX", "Version 12"],
        ["Network", "Broadband Internet"],
        ["Storage", "150 GB SSD"]
      ]
    }
  },
  {
    id: 4,
    title: "God of War",
    price: 19.99,
    originalPrice: 49.99,
    discount: 60,
    platform: "PC",
    genre: "Action",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1593500/capsule_616x353.jpg",
    imageHor: "images/games/godofwar-g/godofwar-horizontal.avif",
    imageVer: "images/games/godofwar-g/godofwar-vertical.jpg",
    description: "Kratos and his son Atreus embark on a dangerous journey through Norse lands. But in this new world, gods and monsters are unlike anything Kratos has faced before.",
    featured: false,
    developer: "Santa Monica Studio",
    publisher: "PlayStation PC LLC",
    releaseDate: "January 14, 2022",
    reviewScore: 95,
    reviewCount: "89,000",
    reviewText: "Overwhelmingly Positive",
    media: [
      { type: "video", src: "images/screenshots/godofwar-s/godofwar-trailer1.mp4", thumb: "images/screenshots/godofwar-s/godofwar-thumb1.jpg" },
      { type: "video", src: "images/screenshots/godofwar-s/godofwar-trailer2.mp4", thumb: "images/screenshots/godofwar-s/godofwar-thumb2.jpg" },
      { type: "image", src: "images/screenshots/godofwar-s/godofwar-ss1.jpg", thumb: "images/screenshots/godofwar-s/godofwar-ss1.jpg" },
      { type: "image", src: "images/screenshots/godofwar-s/godofwar-ss2.jpg", thumb: "images/screenshots/godofwar-s/godofwar-ss2.jpg" },
      { type: "image", src: "images/screenshots/godofwar-s/godofwar-ss3.jpg", thumb: "images/screenshots/godofwar-s/godofwar-ss3.jpg" },
      { type: "image", src: "images/screenshots/godofwar-s/godofwar-ss4.jpg", thumb: "images/screenshots/godofwar-s/godofwar-ss4.jpg" },
      { type: "image", src: "images/screenshots/godofwar-s/godofwar-ss5.jpg", thumb: "images/screenshots/godofwar-s/godofwar-ss5.jpg" }
    ],
    systemReqs: {
      min: [
        ["OS", "Windows 10 64-bit"],
        ["CPU", "Intel Core i5-6600K / AMD Ryzen 5 2600X"],
        ["RAM", "8 GB RAM"],
        ["GPU", "NVIDIA GTX 1060 6 GB / AMD RX 5500 XT 8 GB"],
        ["DirectX", "Version 11"],
        ["Network", "Broadband Internet"],
        ["Storage", "70 GB SSD"]
      ],
      rec: [
        ["OS", "Windows 10 64-bit"],
        ["CPU", "Intel Core i9-9900K / AMD Ryzen 9 3900X"],
        ["RAM", "16 GB RAM"],
        ["GPU", "NVIDIA RTX 3080 / AMD RX 6800 XT"],
        ["DirectX", "Version 12"],
        ["Network", "Broadband Internet"],
        ["Storage", "70 GB SSD"]
      ]
    }
  },
  {
    id: 5,
    title: "Elden Ring",
    price: 34.99,
    originalPrice: 59.99,
    discount: 42,
    platform: "PC",
    genre: "RPG",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/capsule_616x353.jpg",
    imageHor: "images/games/elden-g/elden-horizontal.avif",
    imageVer: "images/games/elden-g/elden-horizontal.avif",
    description: "An open-world fantasy action-RPG from FromSoftware and George R. R. Martin. Journey through a vast world full of danger at every turn and become the Elden Lord.",
    featured: false,
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    releaseDate: "February 25, 2022",
    reviewScore: 94,
    reviewCount: "118,000",
    reviewText: "Overwhelmingly Positive",
    media: [
      { type: "video", src: "images/screenshots/elden-s/eldenring-trailer1.mp4", thumb: "images/screenshots/elden-s/eldenring-thumb1.jpg" },
      { type: "video", src: "images/screenshots/elden-s/eldenring-trailer2.mp4", thumb: "images/screenshots/elden-s/eldenring-thumb2.jpg" },
      { type: "image", src: "images/screenshots/elden-s/eldenring-ss1.jpg", thumb: "images/screenshots/elden-s/eldenring-ss1.jpg" },
      { type: "image", src: "images/screenshots/elden-s/eldenring-ss2.jpg", thumb: "images/screenshots/elden-s/eldenring-ss2.jpg" },
      { type: "image", src: "images/screenshots/elden-s/eldenring-ss3.jpg", thumb: "images/screenshots/elden-s/eldenring-ss3.jpg" },
      { type: "image", src: "images/screenshots/elden-s/eldenring-ss4.jpg", thumb: "images/screenshots/elden-s/eldenring-ss4.jpg" },
      { type: "image", src: "images/screenshots/elden-s/eldenring-ss5.jpg", thumb: "images/screenshots/elden-s/eldenring-ss5.jpg" }
    ],
    systemReqs: {
      min: [
        ["OS", "Windows 10 64-bit"],
        ["CPU", "Intel Core i5-8400 / AMD Ryzen 3 3300X"],
        ["RAM", "12 GB RAM"],
        ["GPU", "NVIDIA GTX 1060 3 GB / AMD RX 580 4 GB"],
        ["DirectX", "Version 12"],
        ["Network", "Broadband Internet"],
        ["Storage", "60 GB SSD"]
      ],
      rec: [
        ["OS", "Windows 10/11 64-bit"],
        ["CPU", "Intel Core i7-8700K / AMD Ryzen 5 3600X"],
        ["RAM", "16 GB RAM"],
        ["GPU", "NVIDIA GTX 1070 8 GB / AMD RX Vega 56 8 GB"],
        ["DirectX", "Version 12"],
        ["Network", "Broadband Internet"],
        ["Storage", "60 GB SSD"]
      ]
    }
  },
  {
    id: 6,
    title: "Hollow Knight",
    price: 2.99,
    originalPrice: 14.99,
    discount: 80,
    platform: "PC",
    genre: "Indie",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/367520/capsule_616x353.jpg",
    imageHor: "images/games/hollow-g/hollow-horizontal.jpg",
    imageVer: "images/games/hollow-g/hollow-vertical.jpg",
    description: "A challenging action-adventure through a vast underground kingdom of bugs.",
    featured: false,
    developer: "Team Cherry",
    publisher: "Team Cherry",
    releaseDate: "February 24, 2017",
    reviewScore: 98,
    reviewCount: "159,000",
    reviewText: "Overwhelmingly Positive",
    media: [
      { type: "video", src: "images/screenshots/hollowknight-trailer1.mp4", thumb: "images/screenshots/hollowknight-thumb1.jpg" },
      { type: "video", src: "images/screenshots/hollowknight-trailer2.mp4", thumb: "images/screenshots/hollowknight-thumb2.jpg" },
      { type: "image", src: "images/screenshots/hollowknight-ss1.jpg", thumb: "images/screenshots/hollowknight-ss1.jpg" },
      { type: "image", src: "images/screenshots/hollowknight-ss2.jpg", thumb: "images/screenshots/hollowknight-ss2.jpg" },
      { type: "image", src: "images/screenshots/hollowknight-ss3.jpg", thumb: "images/screenshots/hollowknight-ss3.jpg" },
      { type: "image", src: "images/screenshots/hollowknight-ss4.jpg", thumb: "images/screenshots/hollowknight-ss4.jpg" },
      { type: "image", src: "images/screenshots/hollowknight-ss5.jpg", thumb: "images/screenshots/hollowknight-ss5.jpg" }
    ]
  },
  {
    id: 7,
    title: "FIFA 24",
    price: 14.99,
    originalPrice: 69.99,
    discount: 79,
    platform: "PC",
    genre: "Sport",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2195250/capsule_616x353.jpg",
    imageHor: "images/games/fifa-g/fifa-horizontal.jpg",
    imageVer: "images/games/fifa-g/fifa-vertical.jpg",
    description: "The world's most popular football simulator with real players and teams.",
    featured: false,
    developer: "EA Sports",
    publisher: "Electronic Arts",
    releaseDate: "September 29, 2023",
    reviewScore: 51,
    reviewCount: "22,000",
    reviewText: "Mixed",
    media: [
      { type: "video", src: "images/screenshots/fifa24-trailer1.mp4", thumb: "images/screenshots/fifa24-thumb1.jpg" },
      { type: "video", src: "images/screenshots/fifa24-trailer2.mp4", thumb: "images/screenshots/fifa24-thumb2.jpg" },
      { type: "image", src: "images/screenshots/fifa24-ss1.jpg", thumb: "images/screenshots/fifa24-ss1.jpg" },
      { type: "image", src: "images/screenshots/fifa24-ss2.jpg", thumb: "images/screenshots/fifa24-ss2.jpg" },
      { type: "image", src: "images/screenshots/fifa24-ss3.jpg", thumb: "images/screenshots/fifa24-ss3.jpg" },
      { type: "image", src: "images/screenshots/fifa24-ss4.jpg", thumb: "images/screenshots/fifa24-ss4.jpg" },
      { type: "image", src: "images/screenshots/fifa24-ss5.jpg", thumb: "images/screenshots/fifa24-ss5.jpg" }
    ]
  },
  {
    id: 8,
    title: "Stardew Valley",
    price: 6.99,
    originalPrice: 13.99,
    discount: 50,
    platform: "PC",
    genre: "Indie",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/413150/capsule_616x353.jpg",
    description: "You've inherited your grandfather's old farm plot. Build up your farm and make new friends.",
    featured: false,
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    releaseDate: "February 26, 2016",
    reviewScore: 98,
    reviewCount: "280,000",
    reviewText: "Overwhelmingly Positive",
    media: [
      { type: "video", src: "images/screenshots/stardewvalley-trailer1.mp4", thumb: "images/screenshots/stardewvalley-thumb1.jpg" },
      { type: "video", src: "images/screenshots/stardewvalley-trailer2.mp4", thumb: "images/screenshots/stardewvalley-thumb2.jpg" },
      { type: "image", src: "images/screenshots/stardewvalley-ss1.jpg", thumb: "images/screenshots/stardewvalley-ss1.jpg" },
      { type: "image", src: "images/screenshots/stardewvalley-ss2.jpg", thumb: "images/screenshots/stardewvalley-ss2.jpg" },
      { type: "image", src: "images/screenshots/stardewvalley-ss3.jpg", thumb: "images/screenshots/stardewvalley-ss3.jpg" },
      { type: "image", src: "images/screenshots/stardewvalley-ss4.jpg", thumb: "images/screenshots/stardewvalley-ss4.jpg" },
      { type: "image", src: "images/screenshots/stardewvalley-ss5.jpg", thumb: "images/screenshots/stardewvalley-ss5.jpg" }
    ]
  },
  {
    id: 9,
    title: "Grand Theft Auto V",
    price: 8.99,
    originalPrice: 29.99,
    discount: 70,
    platform: "PC",
    genre: "Action",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/capsule_616x353.jpg",
    imageHor: "images/games/gta-g/gta-horizontal.webp",
    imageVer: "images/games/gta-g/gta-vertical.jpg",
    description: "Three criminals plan a series of heists while under pressure from government agencies.",
    featured: false,
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    releaseDate: "April 14, 2015",
    reviewScore: 87,
    reviewCount: "388,000",
    reviewText: "Very Positive",
    media: [
      { type: "video", src: "images/screenshots/gtav-trailer1.mp4", thumb: "images/screenshots/gtav-thumb1.jpg" },
      { type: "video", src: "images/screenshots/gtav-trailer2.mp4", thumb: "images/screenshots/gtav-thumb2.jpg" },
      { type: "image", src: "images/screenshots/gtav-ss1.jpg", thumb: "images/screenshots/gtav-ss1.jpg" },
      { type: "image", src: "images/screenshots/gtav-ss2.jpg", thumb: "images/screenshots/gtav-ss2.jpg" },
      { type: "image", src: "images/screenshots/gtav-ss3.jpg", thumb: "images/screenshots/gtav-ss3.jpg" },
      { type: "image", src: "images/screenshots/gtav-ss4.jpg", thumb: "images/screenshots/gtav-ss4.jpg" },
      { type: "image", src: "images/screenshots/gtav-ss5.jpg", thumb: "images/screenshots/gtav-ss5.jpg" }
    ]
  },
{
  id: 10,
  title: "R.E.P.O.",
  price: 6.99,
  originalPrice: 9.99,
  discount: 30,
  platform: "PC",
  genre: "Action",
  image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3241660/capsule_616x353.jpg",
  imageHor: "images/games/repo-g/repo-horizontal.jpg",
  imageVer: "images/games/repo-g/repo-vertical.webp",
  description: "R.E.P.O. is an online co-op horror game with up to 6 players. Locate valuable, fully physics-based objects, handle them carefully, and extract them from terrifying environments while dealing with proximity voice chat, scary monsters, and chaotic teamwork.",
  featured: false,
  developer: "semiwork",
  publisher: "semiwork",
  releaseDate: "February 26, 2025",
  reviewScore: 96,
  reviewCount: "119,394",
  reviewText: "Overwhelmingly Positive",
  media: [
    { type: "video", src: "images/screenshots/repo-trailer1.mp4", thumb: "images/screenshots/repo-thumb1.jpg" },
    { type: "video", src: "images/screenshots/repo-trailer2.mp4", thumb: "images/screenshots/repo-thumb2.jpg" },
    { type: "image", src: "images/screenshots/repo-ss1.jpg", thumb: "images/screenshots/repo-ss1.jpg" },
    { type: "image", src: "images/screenshots/repo-ss2.jpg", thumb: "images/screenshots/repo-ss2.jpg" },
    { type: "image", src: "images/screenshots/repo-ss3.jpg", thumb: "images/screenshots/repo-ss3.jpg" },
    { type: "image", src: "images/screenshots/repo-ss4.jpg", thumb: "images/screenshots/repo-ss4.jpg" },
    { type: "image", src: "images/screenshots/repo-ss5.jpg", thumb: "images/screenshots/repo-ss5.jpg" }
  ],
  systemReqs: {
    min: [
      ["OS", "Windows 10"],
      ["CPU", "Core i5 6600"],
      ["RAM", "8 GB RAM"],
      ["GPU", "GTX 970"],
      ["DirectX", "Version 10"],
      ["Network", "Broadband Internet"],
      ["Storage", "1 GB available space"]
    ],
    rec: [
      ["OS", "Windows 11"],
      ["CPU", "Intel Core i7 8700"],
      ["RAM", "8 GB RAM"],
      ["GPU", "GTX 1070"],
      ["DirectX", "Version 12"],
      ["Network", "Broadband Internet"],
      ["Storage", "1 GB available space"]
    ]
  }
},
  {
    id: 11,
    title: "Spider-Man Miles Morales",
    price: 29.99,
    originalPrice: 49.99,
    discount: 40,
    platform: "PlayStation",
    genre: "Action",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1817070/capsule_616x353.jpg",
    description: "Miles Morales discovers his new powers and steps up to become the new Spider-Man.",
    featured: false,
    developer: "Insomniac Games",
    publisher: "PlayStation PC LLC",
    releaseDate: "November 18, 2022",
    reviewScore: 92,
    reviewCount: "18,000",
    reviewText: "Very Positive",
    media: [
      { type: "video", src: "images/screenshots/spiderman-trailer1.mp4", thumb: "images/screenshots/spiderman-thumb1.jpg" },
      { type: "video", src: "images/screenshots/spiderman-trailer2.mp4", thumb: "images/screenshots/spiderman-thumb2.jpg" },
      { type: "image", src: "images/screenshots/spiderman-ss1.jpg", thumb: "images/screenshots/spiderman-ss1.jpg" },
      { type: "image", src: "images/screenshots/spiderman-ss2.jpg", thumb: "images/screenshots/spiderman-ss2.jpg" },
      { type: "image", src: "images/screenshots/spiderman-ss3.jpg", thumb: "images/screenshots/spiderman-ss3.jpg" },
      { type: "image", src: "images/screenshots/spiderman-ss4.jpg", thumb: "images/screenshots/spiderman-ss4.jpg" },
      { type: "image", src: "images/screenshots/spiderman-ss5.jpg", thumb: "images/screenshots/spiderman-ss5.jpg" }
    ]
  },
  {
    id: 12,
    title: "Minecraft",
    price: 19.99,
    originalPrice: 26.99,
    discount: 26,
    platform: "PC",
    genre: "Sandbox",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1672970/capsule_616x353.jpg",
    description: "Build, survive and explore infinite blocky worlds.",
    featured: false,
    developer: "Mojang Studios",
    publisher: "Mojang Studios",
    releaseDate: "November 18, 2011",
    reviewScore: 95,
    reviewCount: "45,000",
    reviewText: "Overwhelmingly Positive",
    media: [
      { type: "video", src: "images/screenshots/minecraft-trailer1.mp4", thumb: "images/screenshots/minecraft-thumb1.jpg" },
      { type: "video", src: "images/screenshots/minecraft-trailer2.mp4", thumb: "images/screenshots/minecraft-thumb2.jpg" },
      { type: "image", src: "images/screenshots/minecraft-ss1.jpg", thumb: "images/screenshots/minecraft-ss1.jpg" },
      { type: "image", src: "images/screenshots/minecraft-ss2.jpg", thumb: "images/screenshots/minecraft-ss2.jpg" },
      { type: "image", src: "images/screenshots/minecraft-ss3.jpg", thumb: "images/screenshots/minecraft-ss3.jpg" },
      { type: "image", src: "images/screenshots/minecraft-ss4.jpg", thumb: "images/screenshots/minecraft-ss4.jpg" },
      { type: "image", src: "images/screenshots/minecraft-ss5.jpg", thumb: "images/screenshots/minecraft-ss5.jpg" }
    ]
  }
];
